from KMGdata_to_QualityData import createAASQualityDatafromOneRowKMG


dateipfad = "PruefplanValidierungsbauteil1_16.txt"
example_QualityDataAAS = createAASQualityDatafromOneRowKMG(dateipfad)
print(example_QualityDataAAS)